services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "lead"
      POSTGRES_PASSWORD: "lead"
      POSTGRES_DB: "lead"
    volumes:
      - lead:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - lead
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - SERVICES=sns
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
      - lead
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    name: "lead"
    external: true
  lead:
    driver: bridge

volumes:
  lead: